"""add_fk_constraints_and_drop_case_id

Revision ID: fc0ee56264cc
Revises: c57ee6ce64e0
Create Date: 2026-06-29 19:21:32.544170

此文件由 Alembic autogenerate 自动生成或手工编写。
每份迁移脚本必须同时包含 upgrade() 和 downgrade() 函数。

禁止行为：
- 禁止在迁移脚本中硬编码数据库连接串
- 禁止在迁移脚本中使用 async/await 或异步驱动
- 禁止在迁移脚本中执行非迁移相关的 DML 操作
- 禁止使用 op.execute() 拼接用户输入的 SQL 字符串
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fc0ee56264cc"
down_revision: Union[str, None] = "c57ee6ce64e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """执行正向迁移（DDL 操作）。

    所有 DDL 操作通过 Alembic op.* API 执行，在独立 PostgreSQL 事务中运行。
    若迁移涉及 pgvector 扩展（如创建 vector 类型列），
    必须在此函数开头显式执行：
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "case_cards",
        "title",
        existing_type=sa.VARCHAR(length=100),
        comment="卡片标题（通用化干预方案名）",
        existing_comment="卡片标题",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "behavior_type",
        existing_type=sa.VARCHAR(length=20),
        comment="行为类型（自伤/攻击/刻板/逃跑/情绪崩溃/其他）",
        existing_comment="行为类型",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "age_range_min",
        existing_type=sa.INTEGER(),
        comment="适用年龄区间起始值",
        existing_comment="年龄区间起始",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "age_range_max",
        existing_type=sa.INTEGER(),
        comment="适用年龄区间结束值",
        existing_comment="年龄区间结束",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "severity",
        existing_type=sa.VARCHAR(length=10),
        comment="适用严重程度（轻度/中度/重度）",
        existing_comment="严重程度",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "scene",
        existing_type=sa.VARCHAR(length=20),
        comment="发生场景（家庭/学校/公共场合/机构/不限）",
        existing_comment="发生场景",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "ebp_labels",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="NCAEP 28 种循证实践标签",
        existing_comment="NCAEP 循证实践标签",
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::json"),
    )
    op.alter_column(
        "case_cards",
        "family_category",
        existing_type=sa.VARCHAR(length=20),
        comment="家属端展示大类（环境调整/沟通替代/行为塑造/危机安全/社交引导/自我管理）",
        existing_comment="家属端展示大类",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "immediate_action",
        existing_type=sa.TEXT(),
        comment="即时安全干预动作（四段式第一段）",
        existing_comment="即时安全干预动作",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "comforting_phrase",
        existing_type=sa.TEXT(),
        comment="情绪安抚话术（四段式第二段）",
        existing_comment="情绪安抚话术",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "observation_metrics",
        existing_type=sa.TEXT(),
        comment="后续观察指标（四段式第三段）",
        existing_comment="后续观察指标",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "medical_criteria",
        existing_type=sa.TEXT(),
        comment="就医判断标准（四段式第四段）",
        existing_comment="就医判断标准",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "evidence_level",
        existing_type=sa.VARCHAR(length=20),
        comment="循证等级（NCAEP循证实践/机构经验总结/个案观察记录）",
        existing_comment="循证等级",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "caution_notes",
        existing_type=sa.TEXT(),
        comment="禁忌、注意事项与常见误用",
        existing_comment="禁忌与常见误用",
        existing_nullable=False,
        existing_server_default=sa.text("''::text"),
    )
    op.alter_column(
        "case_cards",
        "contraindications",
        existing_type=sa.TEXT(),
        comment="明确不适用的人群或场景",
        existing_comment="不适用人群/场景",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "attachment_refs",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="附件引用列表（选填）",
        existing_comment="附件引用（选填）",
        existing_nullable=True,
        existing_server_default=sa.text("'[]'::json"),
    )
    op.alter_column(
        "case_cards",
        "review_status",
        existing_type=postgresql.ENUM("draft", "pending_review", "approved", "rejected", name="card_review_status"),
        comment="卡片审核状态（draft/pending_review/approved/rejected）",
        existing_comment="卡片审核状态",
        existing_nullable=False,
        existing_server_default=sa.text("'draft'::card_review_status"),
    )
    op.alter_column(
        "case_cards",
        "index_status",
        existing_type=postgresql.ENUM(
            "pending",
            "processing",
            "indexed",
            "indexing_failed",
            name="card_index_status_enum",
        ),
        comment="向量化索引状态（pending/processing/indexed/indexing_failed）",
        existing_comment="向量化索引状态",
        existing_nullable=True,
    )
    op.alter_column(
        "case_cards",
        "inferred_fields",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="LLM 提取时推断的字段及依据，供专家审核确认",
        existing_comment="LLM 推断字段及依据",
        existing_nullable=True,
    )
    op.alter_column(
        "case_chunks",
        "card_id",
        existing_type=sa.UUID(),
        comment="关联的 L2 卡片标识，FK → case_cards.card_id",
        existing_nullable=False,
    )
    op.alter_column(
        "case_chunks",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="结构化元数据：behavior_type, age_range, emotion_level, evidence_level, case_title, case_created_at, source, status, vectorized, applicable_tags",
        existing_comment="结构化元数据：behavior_type, age_range, severity, evidence_level",
        existing_nullable=True,
    )
    op.add_column(
        "case_narratives",
        sa.Column(
            "is_seed",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="是否为种子脚本注入的数据",
        ),
    )
    op.alter_column(
        "case_narratives",
        "title",
        existing_type=sa.VARCHAR(length=100),
        comment="叙事标题（通用化描述）",
        existing_comment="叙事标题",
        existing_nullable=False,
    )
    op.alter_column(
        "case_narratives",
        "source_type",
        existing_type=sa.VARCHAR(length=20),
        comment="案例来源类型（专家撰写/机构脱敏/工单沉淀）",
        existing_comment="案例来源类型",
        existing_nullable=False,
    )
    # 旧 author_id 可能包含非 UUID 占位符（如 'seed-script'），
    # 先允许 NULL，清空数据，再用 USING 子句显式转换为 UUID。
    op.alter_column(
        "case_narratives",
        "author_id",
        existing_type=sa.VARCHAR(length=36),
        nullable=True,
        existing_comment="撰写专家标识",
    )
    op.execute("UPDATE case_narratives SET author_id = NULL")
    op.execute("ALTER TABLE case_narratives ALTER COLUMN author_id TYPE UUID USING author_id::uuid")
    op.alter_column(
        "case_narratives",
        "author_id",
        existing_type=sa.UUID(),
        nullable=True,
        comment="撰写专家标识（UUID）",
        existing_comment="撰写专家标识",
    )
    op.alter_column(
        "case_narratives",
        "status",
        existing_type=postgresql.ENUM("draft", "pending_review", "approved", "rejected", name="narrative_status"),
        comment="叙事状态（draft/pending_review/approved/rejected）",
        existing_comment="叙事状态",
        existing_nullable=False,
        existing_server_default=sa.text("'draft'::narrative_status"),
    )
    op.alter_column(
        "case_narratives",
        "derived_card_ids",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="衍生的 L2 卡片 card_id 列表（JSON 数组）",
        existing_comment="衍生的 L2 卡片 ID 列表",
        existing_nullable=True,
    )
    op.alter_column(
        "case_narratives",
        "extraction_status",
        existing_type=sa.VARCHAR(length=20),
        comment="LLM 提取状态（pending/extracting/extracted/failed）",
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.create_index(op.f("ix_case_narratives_is_seed"), "case_narratives", ["is_seed"], unique=False)
    op.create_foreign_key(
        op.f("fk_case_narratives_author_id_users"),
        "case_narratives",
        "users",
        ["author_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # case_reviews 当前为空，直接显式转换类型。
    op.execute("ALTER TABLE case_reviews ALTER COLUMN case_id TYPE UUID USING case_id::uuid")
    op.execute("ALTER TABLE case_reviews ALTER COLUMN reviewer_id TYPE UUID USING reviewer_id::uuid")
    op.alter_column(
        "case_reviews",
        "case_id",
        existing_type=sa.UUID(),
        comment="关联的 L2 卡片标识（FK → case_cards.card_id）",
        existing_comment="关联的案例标识（FK → cases.case_id）",
        existing_nullable=False,
    )
    op.alter_column(
        "case_reviews",
        "ai_review_report",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="AI 预审完整报告（JSONB，含四项检查结果和 overall 结论）",
        existing_comment="AI 预审完整报告（JSONB）",
        existing_nullable=True,
    )
    op.alter_column(
        "case_reviews",
        "reviewer_id",
        existing_type=sa.UUID(),
        nullable=True,
        existing_comment="审核人标识（UUID）",
    )
    op.create_foreign_key(
        op.f("fk_case_reviews_reviewer_id_users"),
        "case_reviews",
        "users",
        ["reviewer_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_case_reviews_case_id_case_cards"),
        "case_reviews",
        "case_cards",
        ["case_id"],
        ["card_id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "consultations",
        "user_id",
        existing_type=sa.UUID(),
        nullable=True,
        comment="本次咨询的发起家属用户 UUID（FK 到 users 表）",
        existing_comment="本次咨询的发起家属用户 UUID（逻辑 FK 到 users 表）",
    )
    op.alter_column(
        "consultations",
        "consultation_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="咨询发生时间（服务端时间，由 PostgreSQL NOW() 自动填充）",
        existing_comment="咨询发生时间（服务端时间，由 PostgreSQL NOW() 自动填充，覆盖客户端传入值）",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "consultations",
        "source_list",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="被引用案例的来源信息列表（JSONB 数组）",
        existing_comment="被引用案例的来源信息列表（JSONB 字符串数组）",
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "consultations",
        "disclaimer",
        existing_type=sa.TEXT(),
        comment="合规免责声明固定文本",
        existing_comment="合规免责声明固定文本（入库前等值校验）",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_consultations_request_id"), table_name="consultations")
    op.create_foreign_key(
        op.f("fk_consultations_user_id_users"),
        "consultations",
        "users",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "event_logs",
        "recorded_by",
        existing_type=sa.UUID(),
        nullable=True,
        existing_comment="记录人用户 UUID",
    )
    op.create_foreign_key(
        op.f("fk_event_logs_recorded_by_users"),
        "event_logs",
        "users",
        ["recorded_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_event_logs_profile_id_profiles"),
        "event_logs",
        "profiles",
        ["profile_id"],
        ["profile_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_profiles_caregiver_id_users"),
        "profiles",
        "users",
        ["caregiver_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # review_audit_logs 当前为空，直接显式转换类型。
    op.execute("ALTER TABLE review_audit_logs ALTER COLUMN case_id TYPE UUID USING case_id::uuid")
    op.execute("ALTER TABLE review_audit_logs ALTER COLUMN operator_id TYPE UUID USING operator_id::uuid")
    op.alter_column(
        "review_audit_logs",
        "case_id",
        existing_type=sa.UUID(),
        comment="关联的 L2 卡片标识",
        existing_comment="关联的案例标识",
        existing_nullable=False,
    )
    op.alter_column(
        "review_audit_logs",
        "operator_id",
        existing_type=sa.UUID(),
        nullable=True,
        existing_comment="操作人 UUID",
    )
    op.create_foreign_key(
        op.f("fk_review_audit_logs_case_id_case_cards"),
        "review_audit_logs",
        "case_cards",
        ["case_id"],
        ["card_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_review_audit_logs_operator_id_users"),
        "review_audit_logs",
        "users",
        ["operator_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_teacher_links_teacher_id_users"),
        "teacher_links",
        "users",
        ["teacher_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_teacher_links_profile_id_profiles"),
        "teacher_links",
        "profiles",
        ["profile_id"],
        ["profile_id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=32),
        comment="登录名称，全局唯一（大小写不敏感唯一性由 Repository 层 LOWER() 查询保证）",
        existing_comment="登录名称，全局唯一（大小写不敏感）",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "device_id",
        existing_type=sa.VARCHAR(length=32),
        comment="小程序匿名设备标识，MVP 阶段替代认证",
        existing_nullable=True,
    )
    op.drop_constraint(op.f("users_device_id_key"), "users", type_="unique")
    op.create_unique_constraint(op.f("uq_users_device_id"), "users", ["device_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """执行逆向迁移（DDL 逆向操作）。

    必须与 upgrade() 的操作一一对应。
    downgrade() 中禁止 DROP EXTENSION vector（除非确认仅由本迁移使用）。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_device_id"), "users", type_="unique")
    op.create_unique_constraint(
        op.f("users_device_id_key"),
        "users",
        ["device_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "users",
        "device_id",
        existing_type=sa.VARCHAR(length=32),
        comment=None,
        existing_comment="小程序匿名设备标识，MVP 阶段替代认证",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=32),
        comment="登录名称，全局唯一（大小写不敏感）",
        existing_comment="登录名称，全局唯一（大小写不敏感唯一性由 Repository 层 LOWER() 查询保证）",
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("fk_teacher_links_profile_id_profiles"),
        "teacher_links",
        type_="foreignkey",
    )
    op.drop_constraint(op.f("fk_teacher_links_teacher_id_users"), "teacher_links", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_review_audit_logs_operator_id_users"),
        "review_audit_logs",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_review_audit_logs_case_id_case_cards"),
        "review_audit_logs",
        type_="foreignkey",
    )
    op.alter_column(
        "review_audit_logs",
        "operator_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=36),
        nullable=False,
        existing_comment="操作人 UUID",
    )
    op.alter_column(
        "review_audit_logs",
        "case_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=36),
        comment="关联的案例标识",
        existing_comment="关联的 L2 卡片标识",
        existing_nullable=False,
    )
    op.drop_constraint(op.f("fk_profiles_caregiver_id_users"), "profiles", type_="foreignkey")
    op.drop_constraint(op.f("fk_event_logs_profile_id_profiles"), "event_logs", type_="foreignkey")
    op.drop_constraint(op.f("fk_event_logs_recorded_by_users"), "event_logs", type_="foreignkey")
    op.alter_column(
        "event_logs",
        "recorded_by",
        existing_type=sa.UUID(),
        nullable=False,
        existing_comment="记录人用户 UUID",
    )
    op.drop_constraint(op.f("fk_consultations_user_id_users"), "consultations", type_="foreignkey")
    op.create_index(
        op.f("ix_consultations_request_id"),
        "consultations",
        ["request_id"],
        unique=True,
    )
    op.alter_column(
        "consultations",
        "disclaimer",
        existing_type=sa.TEXT(),
        comment="合规免责声明固定文本（入库前等值校验）",
        existing_comment="合规免责声明固定文本",
        existing_nullable=False,
    )
    op.alter_column(
        "consultations",
        "source_list",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="被引用案例的来源信息列表（JSONB 字符串数组）",
        existing_comment="被引用案例的来源信息列表（JSONB 数组）",
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "consultations",
        "consultation_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="咨询发生时间（服务端时间，由 PostgreSQL NOW() 自动填充，覆盖客户端传入值）",
        existing_comment="咨询发生时间（服务端时间，由 PostgreSQL NOW() 自动填充）",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "consultations",
        "user_id",
        existing_type=sa.UUID(),
        nullable=False,
        comment="本次咨询的发起家属用户 UUID（逻辑 FK 到 users 表）",
        existing_comment="本次咨询的发起家属用户 UUID（FK 到 users 表）",
    )
    op.drop_constraint(op.f("fk_case_reviews_case_id_case_cards"), "case_reviews", type_="foreignkey")
    op.drop_constraint(op.f("fk_case_reviews_reviewer_id_users"), "case_reviews", type_="foreignkey")
    op.alter_column(
        "case_reviews",
        "reviewer_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=36),
        nullable=False,
        existing_comment="审核人标识（UUID）",
    )
    op.alter_column(
        "case_reviews",
        "ai_review_report",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="AI 预审完整报告（JSONB）",
        existing_comment="AI 预审完整报告（JSONB，含四项检查结果和 overall 结论）",
        existing_nullable=True,
    )
    op.alter_column(
        "case_reviews",
        "case_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=36),
        comment="关联的案例标识（FK → cases.case_id）",
        existing_comment="关联的 L2 卡片标识（FK → case_cards.card_id）",
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("fk_case_narratives_author_id_users"),
        "case_narratives",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_case_narratives_is_seed"), table_name="case_narratives")
    op.alter_column(
        "case_narratives",
        "extraction_status",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="LLM 提取状态（pending/extracting/extracted/failed）",
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "case_narratives",
        "derived_card_ids",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="衍生的 L2 卡片 ID 列表",
        existing_comment="衍生的 L2 卡片 card_id 列表（JSON 数组）",
        existing_nullable=True,
    )
    op.alter_column(
        "case_narratives",
        "status",
        existing_type=postgresql.ENUM("draft", "pending_review", "approved", "rejected", name="narrative_status"),
        comment="叙事状态",
        existing_comment="叙事状态（draft/pending_review/approved/rejected）",
        existing_nullable=False,
        existing_server_default=sa.text("'draft'::narrative_status"),
    )
    # 正向迁移已丢失非 UUID 的 author_id 原始值，回滚时无法恢复 NOT NULL。
    # 保持 nullable 以避免现有 NULL 数据阻塞 downgrade。
    op.alter_column(
        "case_narratives",
        "author_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=36),
        nullable=True,
        comment="撰写专家标识",
        existing_comment="撰写专家标识（UUID）",
    )
    op.alter_column(
        "case_narratives",
        "source_type",
        existing_type=sa.VARCHAR(length=20),
        comment="案例来源类型",
        existing_comment="案例来源类型（专家撰写/机构脱敏/工单沉淀）",
        existing_nullable=False,
    )
    op.alter_column(
        "case_narratives",
        "title",
        existing_type=sa.VARCHAR(length=100),
        comment="叙事标题",
        existing_comment="叙事标题（通用化描述）",
        existing_nullable=False,
    )
    op.drop_column("case_narratives", "is_seed")
    op.alter_column(
        "case_chunks",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="结构化元数据：behavior_type, age_range, severity, evidence_level",
        existing_comment="结构化元数据：behavior_type, age_range, emotion_level, evidence_level, case_title, case_created_at, source, status, vectorized, applicable_tags",
        existing_nullable=True,
    )
    op.alter_column(
        "case_chunks",
        "card_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="关联的 L2 卡片标识，FK → case_cards.card_id",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "inferred_fields",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="LLM 推断字段及依据",
        existing_comment="LLM 提取时推断的字段及依据，供专家审核确认",
        existing_nullable=True,
    )
    op.alter_column(
        "case_cards",
        "index_status",
        existing_type=postgresql.ENUM(
            "pending",
            "processing",
            "indexed",
            "indexing_failed",
            name="card_index_status_enum",
        ),
        comment="向量化索引状态",
        existing_comment="向量化索引状态（pending/processing/indexed/indexing_failed）",
        existing_nullable=True,
    )
    op.alter_column(
        "case_cards",
        "review_status",
        existing_type=postgresql.ENUM("draft", "pending_review", "approved", "rejected", name="card_review_status"),
        comment="卡片审核状态",
        existing_comment="卡片审核状态（draft/pending_review/approved/rejected）",
        existing_nullable=False,
        existing_server_default=sa.text("'draft'::card_review_status"),
    )
    op.alter_column(
        "case_cards",
        "attachment_refs",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="附件引用（选填）",
        existing_comment="附件引用列表（选填）",
        existing_nullable=True,
        existing_server_default=sa.text("'[]'::json"),
    )
    op.alter_column(
        "case_cards",
        "contraindications",
        existing_type=sa.TEXT(),
        comment="不适用人群/场景",
        existing_comment="明确不适用的人群或场景",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "caution_notes",
        existing_type=sa.TEXT(),
        comment="禁忌与常见误用",
        existing_comment="禁忌、注意事项与常见误用",
        existing_nullable=False,
        existing_server_default=sa.text("''::text"),
    )
    op.alter_column(
        "case_cards",
        "evidence_level",
        existing_type=sa.VARCHAR(length=20),
        comment="循证等级",
        existing_comment="循证等级（NCAEP循证实践/机构经验总结/个案观察记录）",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "medical_criteria",
        existing_type=sa.TEXT(),
        comment="就医判断标准",
        existing_comment="就医判断标准（四段式第四段）",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "observation_metrics",
        existing_type=sa.TEXT(),
        comment="后续观察指标",
        existing_comment="后续观察指标（四段式第三段）",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "comforting_phrase",
        existing_type=sa.TEXT(),
        comment="情绪安抚话术",
        existing_comment="情绪安抚话术（四段式第二段）",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "immediate_action",
        existing_type=sa.TEXT(),
        comment="即时安全干预动作",
        existing_comment="即时安全干预动作（四段式第一段）",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "family_category",
        existing_type=sa.VARCHAR(length=20),
        comment="家属端展示大类",
        existing_comment="家属端展示大类（环境调整/沟通替代/行为塑造/危机安全/社交引导/自我管理）",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "ebp_labels",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="NCAEP 循证实践标签",
        existing_comment="NCAEP 28 种循证实践标签",
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::json"),
    )
    op.alter_column(
        "case_cards",
        "scene",
        existing_type=sa.VARCHAR(length=20),
        comment="发生场景",
        existing_comment="发生场景（家庭/学校/公共场合/机构/不限）",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "severity",
        existing_type=sa.VARCHAR(length=10),
        comment="严重程度",
        existing_comment="适用严重程度（轻度/中度/重度）",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "age_range_max",
        existing_type=sa.INTEGER(),
        comment="年龄区间结束",
        existing_comment="适用年龄区间结束值",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "age_range_min",
        existing_type=sa.INTEGER(),
        comment="年龄区间起始",
        existing_comment="适用年龄区间起始值",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "behavior_type",
        existing_type=sa.VARCHAR(length=20),
        comment="行为类型",
        existing_comment="行为类型（自伤/攻击/刻板/逃跑/情绪崩溃/其他）",
        existing_nullable=False,
    )
    op.alter_column(
        "case_cards",
        "title",
        existing_type=sa.VARCHAR(length=100),
        comment="卡片标题",
        existing_comment="卡片标题（通用化干预方案名）",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
